# Project-wide Gradle settings.

# JVM settings
org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Enable non-transitive R classes
android.nonTransitiveRClass=true

# Disable Gradle daemon problems on Termux
org.gradle.daemon=false

# Use a single worker (better for Termux)
org.gradle.workers.max=1

# Disable parallel build
org.gradle.parallel=false
#android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
